### ISSUE TITLE
README mentions postgres tags and unsupported features

### ISSUE THREAD

**Issue by spantaleev** [mother-of-all-self-hosting/ansible-role-postgis#1]
The README mentions `upgrade-postgres` and other such tags, which don't exist.
If they are expected to work well, you can adjust the references (e.g. `upgrade-postgis`). If not, you can remove these references.

"import data from SQLite, NeDB, etc" is also mentioned. I believe support for this has been removed from this role (after forking from the Postgres role).

The exampe code shows things like `postgis_base_path: "{{ my_base_path }}/postgres"`, which should probably be adjusted to use `postgis` instead of `postgres`.

----

`Project source code URL: https://github.com/postgres/postgres` in `defaults/main.yml` is outdated.

------

All `postgis_pgloader_` variables are probably unnecessary and can be removed?

**Comment by moan0s** [comment]
Thanks a lot, should all be fixed now!
